blueprint:
  name: deCONZ - IKEA on/off switch
  description: |
    "Control your deCONZ light(s) with IKEA Tradfri on/off switch
    
    Select the Tradfri remote and your lights.
    You can turn the lights On / Off, or hold the buttons to dim the lights"
  domain: automation
  input:
    remote:
      name: Remote
      description: The remote that will control the lights
      selector:
        device:
          integration: deconz
          manufacturer: 'IKEA of Sweden'
          model: 'TRADFRI on/off switch'
    light:
      name: Light
      description: The lights that will be controlled
      selector:
        target:
          entity:
            domain: light
    switch:
      name: Switch
      description: The swithces that will be controlled
      selector:
        target:
          entity:
            domain: switch

mode: restart

trigger:
- platform: event
  event_type: deconz_event
  event_data:
    device_id: !input 'remote'

action:
- variables:
    event: "{{ trigger.event.data.event }}"

- choose:
  - conditions:
    - "{{ event == 1002 }}"
    sequence:
    - service: light.turn_on
      target: !input 'light'
    - service: switch.turn_on
      target: !input 'switch'      
  - conditions:
    - "{{ event == 2002 }}"
    sequence:
    - service: light.turn_off
      target: !input 'light'
    - service: switch.turn_off
      target: !input 'switch'
